{% set name = "pyca" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 284829b102afbb4b1eb34ce18b84e209dad43bec614ea89c6776462620e52176
  patches:
    - 0001-setup.patch

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  skip: true   # [win]
  missing_dso_whitelist:
    - '*/libca.*'
    - '*/libCom.*'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - epicscorelibs {{ epicscorelibs }}
    - numpy
    - pip
    - setuptools
    - setuptools_dso
  run:
    - python
    - epicscorelibs {{ epicscorelibs }}
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyca
    - psp

about:
  home: https://github.com/slaclab/pyca
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: PyCA - lightweight bindings for Python applications to access EPICS PVs.

  description: |
    PyCA (Python Channel Access) is a module that offers lightweight
    bindings for Python applications to access EPICS PVs. It acts as
    a channel access client, much like pyepics. The intention of the 
    module is to provide better performance for embedded applications,
    rather than to provide an interactive interface. The most significant
    gains will be found when monitoring large waveforms that need to be
    processed before exposing them the Python layer.      
  dev_url: https://github.com/slaclab/pyca

extra:
  recipe-maintainers:
    - klauer
    - zllentz
