{% set name = "pyca" %}
{% set version = "3.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/{{ name }}/archive/{{ version }}.tar.gz
  sha256: e7bf73a7f22986df22625e27ad25b1e7b3639db7424d6d21608f3603389c6cc4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]
  missing_dso_whitelist:
    - '*/libca.*'
    - '*/libCom.*'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - epicscorelibs {{ epicscorelibs }}
    - numpy
    - pip
    - setuptools
    - setuptools_dso
    - setuptools_scm
  run:
    - python
    - epicscorelibs {{ epicscorelibs }}
    - numpy >=1.24
test:
  imports:
    - pyca
    - psp

about:
  home: https://github.com/slaclab/pyca
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: PyCA - lightweight bindings for Python applications to access EPICS PVs.

  description: |
    PyCA (Python Channel Access) is a module that offers lightweight
    bindings for Python applications to access EPICS PVs. It acts as
    a channel access client, much like pyepics. The intention of the 
    module is to provide better performance for embedded applications,
    rather than to provide an interactive interface. The most significant
    gains will be found when monitoring large waveforms that need to be
    processed before exposing them the Python layer.      
  dev_url: https://github.com/slaclab/pyca

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
